name: Omnixys Maven Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

concurrency:
  group: pipeline-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  pull-requests: write
  issues: write
  id-token: write

env:
  COSIGN_EXPERIMENTAL: 'true'
  IMAGE_NAME: ${{ secrets.DOCKER_USER }}/${{ vars.SERVICE }}-service
  IMAGE_NAME_REPOSITORY: ghcr.io/${{ github.repository }}

jobs:
  ci:
    name: 🧪 CI – Build (Maven / Java ${{ matrix.java-version }})
    runs-on: ubuntu-latest

    if: >
      !contains(github.event.head_commit.message, 'chore(release)')

    strategy:
      matrix:
        java-version: [26]
        node-version: [24]

    steps:
      - name: 🧾 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ☕ Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ matrix.java-version }}
          cache: maven

      - name: 🔐 Configure Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
             <servers>
                 <server>
                     <id>github</id>
                     <username>${GPR_USER}</username>
                        <password>${GPR_KEY}</password>
                 </server>
             
                     <server>
                     <id>github-starter</id>
                     <username>${GPR_USER}</username>
                        <password>${GPR_KEY}</password>
                 </server>
             
                         <server>
                     <id>github-bom</id>
                     <username>${GPR_USER}</username>
                        <password>${GPR_KEY}</password>
                 </server>
             
                     <server>
                   <id>github-observability</id>
                     <username>${GPR_USER}</username>
                        <password>${GPR_KEY}</password>
                 </server>
             
                 <server>
                   <id>github-kafka</id>
                     <username>${GPR_USER}</username>
                        <password>${GPR_KEY}</password>
                 </server>
             
                 <server>
                   <id>github-logger</id>
                     <username>${GPR_USER}</username>
                        <password>${GPR_KEY}</password>
                 </server>
             

             </servers>
          </settings>
          EOF
        env:
          GPR_USER: ${{ github.actor }}
          GPR_KEY: ${{ secrets.OMNIXYS_TOKEN }}

      - name: 📦 Build
        run: mvn -B clean verify

  release:
    name: 🚀 Release (semantic-release)
    runs-on: ubuntu-latest
    needs: ci

    strategy:
      matrix:
        java-version: [26]
        node-version: [24]

    outputs:
      released: ${{ steps.semantic.outputs.released }}
      version: ${{ steps.read_version.outputs.version }}

    steps:
      - name: 🧾 Checkout (FULL HISTORY)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ⚙️ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📦 Install semantic-release deps
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: 🔐 Configure Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
             <servers>          
                     <server>
                     <id>github-starter</id>
                     <username>${GPR_USER}</username>
                        <password>${GPR_KEY}</password>
                 </server>
             
                         <server>
                     <id>github-bom</id>
                     <username>${GPR_USER}</username>
                        <password>${GPR_KEY}</password>
                 </server>
             </servers>
          </settings>
          EOF
        env:
          GPR_USER: ${{ github.actor }}
          GPR_KEY: ${{ secrets.OMNIXYS_TOKEN }}

      - name: 🚀 Run semantic-release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release | tee log.txt

          if grep -q "Published release" log.txt; then
            echo "released=true" >> $GITHUB_OUTPUT
          else
            echo "released=false" >> $GITHUB_OUTPUT
          fi

      - name: Read version
        id: read_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          DATE=$(date -u +'%Y-%m-%d')

          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "date=$DATE" >> "$GITHUB_OUTPUT"

  push-docker:
    name: 🐳 Build & Push Multi-Arch Images (Docker)
    runs-on: ubuntu-latest
    env:
      CURRENT_VERSION: ${{ needs.release.outputs.version }}

    needs: release
    if: needs.release.outputs.released == 'true'

    strategy:
      matrix:
        java-version: [26]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔐 Configure Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
             <servers>
                 <server>
                     <id>github</id>
                     <username>${GPR_USER}</username>
                        <password>${GPR_KEY}</password>
                 </server>
          
                     <server>
                     <id>github-starter</id>
                     <username>${GPR_USER}</username>
                        <password>${GPR_KEY}</password>
                 </server>
          
                         <server>
                     <id>github-bom</id>
                     <username>${GPR_USER}</username>
                        <password>${GPR_KEY}</password>
                 </server>
          
                     <server>
                   <id>github-observability</id>
                     <username>${GPR_USER}</username>
                        <password>${GPR_KEY}</password>
                 </server>
          
                 <server>
                   <id>github-kafka</id>
                     <username>${GPR_USER}</username>
                        <password>${GPR_KEY}</password>
                 </server>
          
                 <server>
                   <id>github-logger</id>
                     <username>${GPR_USER}</username>
                        <password>${GPR_KEY}</password>
                 </server>
             </servers>
          </settings>
          EOF
        env:
          GPR_USER: ${{ github.actor }}
          GPR_KEY: ${{ secrets.OMNIXYS_TOKEN }}

      - run: |
          git fetch origin main
          git checkout origin/main

      - run: grep -m1 "<version>" pom.xml

      - name: ☕ Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ matrix.java-version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: image=moby/buildkit:latest

      - name: 🔑 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ github.sha }}
          restore-keys: |
            buildx-

      - name: Build and Push Docker Image (Multi-Arch)
        uses: docker/build-push-action@v5
        with:
          secrets: |
            gpr_user=${{ github.actor }}
            gpr_key=${{ secrets.OMNIXYS_TOKEN }}
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:${{ needs.release.outputs.version }}
            ${{ env.IMAGE_NAME }}:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ needs.release.outputs.version }}
            org.opencontainers.image.description=Omnixys Microservice – ${{ env.IMAGE_NAME }}
            org.opencontainers.image.licenses=GPL-3.0-or-later
          build-args: |
            REVISION=${{ github.sha }}
            CREATED=${{ vars.CURRENT_DATE }}
            APP_VERSION=${{ needs.release.outputs.version }}
            APP_NAME=${{ vars.SERVICE }}
            JAVA_VERSION=${{ matrix.java-version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign Docker Image with cosign (OIDC/GitHub)
        run: |
          cosign sign --yes --recursive ${{ env.IMAGE_NAME }}:${{ needs.release.outputs.version }}
          cosign sign --yes --recursive ${{ env.IMAGE_NAME }}:latest



  push-github:
    env:
      CURRENT_VERSION: ${{ needs.release.outputs.version }}
    name: 🐳 Build & Push Multi-Arch Images (Github)
    runs-on: ubuntu-latest

    needs: release
    if: needs.release.outputs.released == 'true'

    strategy:
      matrix:
        java-version: [26]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔐 Configure Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
             <servers>
                 <server>
                     <id>github</id>
                     <username>${GPR_USER}</username>
                        <password>${GPR_KEY}</password>
                 </server>
          
                     <server>
                     <id>github-starter</id>
                     <username>${GPR_USER}</username>
                        <password>${GPR_KEY}</password>
                 </server>
          
                         <server>
                     <id>github-bom</id>
                     <username>${GPR_USER}</username>
                        <password>${GPR_KEY}</password>
                 </server>
          
                     <server>
                   <id>github-observability</id>
                     <username>${GPR_USER}</username>
                        <password>${GPR_KEY}</password>
                 </server>
          
                 <server>
                   <id>github-kafka</id>
                     <username>${GPR_USER}</username>
                        <password>${GPR_KEY}</password>
                 </server>
          
                 <server>
                   <id>github-logger</id>
                     <username>${GPR_USER}</username>
                        <password>${GPR_KEY}</password>
                 </server>
          

             </servers>
          </settings>
          EOF
        env:
          GPR_USER: ${{ github.actor }}
          GPR_KEY: ${{ secrets.OMNIXYS_TOKEN }}

      - run: |
          git fetch origin main
          git checkout origin/main

      - run: grep -m1 "<version>" pom.xml

      - name: ☕ Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ matrix.java-version }}

      - name: 📦 Extract version
        run: |
          VERSION=$(grep -m1 "<version>" pom.xml | sed -E 's/.*<version>(.*)<\/version>.*/\1/')
          echo "CURRENT_VERSION=$VERSION" >> $GITHUB_ENV
          echo "CURRENT_DATE=$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: image=moby/buildkit:latest

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.OMNIXYS_TOKEN }}

      - name: Set up Docker Cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ github.sha }}
          restore-keys: |
            buildx-

      - name: Build and Push Docker Image (GHCR)
        uses: docker/build-push-action@v5
        with:
          secrets: |
            gpr_user=${{ github.actor }}
            gpr_key=${{ secrets.OMNIXYS_TOKEN }}
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME_REPOSITORY }}:${{ needs.release.outputs.version }}
            ${{ env.IMAGE_NAME_REPOSITORY }}:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ needs.release.outputs.version }}
            org.opencontainers.image.description=Omnixys Microservice – ${{ env.IMAGE_NAME }}
            org.opencontainers.image.licenses=GPL-3.0-or-later
          build-args: |
            REVISION=${{ github.sha }}
            CREATED=${{ vars.CURRENT_DATE }}
            APP_VERSION=${{ needs.release.outputs.version }}
            APP_NAME=${{ vars.SERVICE }}
            JAVA_VERSION=${{ matrix.java-version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign Docker Image with cosign (OIDC/GitHub)
        run: |
          cosign sign --yes --recursive ${{ env.IMAGE_NAME_REPOSITORY }}:${{ needs.release.outputs.version }}
          cosign sign --yes --recursive ${{ env.IMAGE_NAME_REPOSITORY }}:latest

