name: Release

on:
  workflow_dispatch:

  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  #   types:
  #     - closed

jobs:
  release:
    # if: ${{ github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 🔐 Setup SSH (Deploy Key)
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.RELEASE_DEPLOY_KEY }}

      - name: 🔁 Switch git remote to SSH
        run: |
          git remote set-url origin git@github.com:omnixys/address-service.git
          git config user.name "omnixys-release-bot"
          git config user.email "release@omnixys.com"

      - name: ⚙️ Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.24.0

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '26.8.1'
          cache: 'pnpm'

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Semantic Release
        run: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
